#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

image() {
    chafa "$1" -f sixel -s "$(($2-2))x$(($3-2))" --animate false --fill block --polite on -t 1 --bg "#282828" && exit 0
    # chafa "$1" -f sixel -s "$(($2-2))x$(($3-2))" --animate false --fill block && exit 0
}

case "$(mimetype -b "$1")" in
image/avif)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && magick "$1" "$CACHE.jpg"
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
image/vnd.djvu+multipage)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | magick -density 200 - "$CACHE.jpg" >/dev/null 2>&1
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
image/svg+xml)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && inkscape --convert-dpi-method=none -o "$CACHE.png" --export-overwrite -D --export-png-color-mode=RGBA_16 "$1"
    image "$CACHE.png" "$2" "$3" "$1"
    ;;
image/x-xcf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE.jpg" ] && magick "$1[0]" "$CACHE.jpg"
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
image/*) image "$1" "$2" "$3" "$1" ;;
application/x-troff-man) man ./ "$1" | col -b ;;
text/*|*/xml|application/x-desktop|application/json|application/x-ndjson|application/mbox|audio/x-mod|application/x-shellscript|inode/symlink) bat --color=always -p --theme gruvbox-dark "$1" ;;
audio/*|application/octet-stream) 
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -m 100%
    image "$CACHE" "$2" "$3" "$1"
    ;;
video/*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -m 100%
    image "$CACHE" "$2" "$3" "$1"
    ;;
*/pdf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
*/epub+zip|*/mobi*|*/x-mobipocket-ebook)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && ebook-meta "$1" --get-cover="$CACHE.jpg" >/dev/null 2>&1
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
application/*zip) atool --list -- "$1" ;;
application/pgp-encrypted) gpg -d -- "$1" ;;
*) exiftool "$1" ;;
esac
exit 1
