#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"
IFS="${IFS%_}"

image() {

    chafa -f sixel -s "$2x$3" --animate off --polite on -t 1 --bg "#282828" "$1"

}

case "$(file --mime-type -Lb "$1")" in
image/avif)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && magick "$1" "$CACHE.jpg"
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
image/vnd.djvu*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | magick -density 200 - "$CACHE.jpg" >/dev/null 2>&1
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
image/*) image "$1" "$2" "$3" ;;
text/troff) man ./ "$1" | col -b ;;
text/*|*/xml|application/x-desktop|application/json|application/x-ndjson|application/mbox|audio/x-mod|application/x-shellscript|inode/symlink|application/vnd.ms-publisher|application/pgp-signature|application/x-trash|application/x-wine-extension-ini)
    bat --color=always -p --theme gruvbox-dark "$1" ;;
audio/ogg) mediainfo "$1" ;;
audio/mpeg)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1).jpg"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -m 100%
    image "$CACHE" "$2" "$3" "$1"
    ;;
video/*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -m 100%
    image "$CACHE" "$2" "$3" "$1"
    ;;
*/pdf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
*/epub+zip|*/mobi*|*/x-mobipocket-ebook)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && ebook-meta "$1" --get-cover="$CACHE.jpg" >/dev/null 2>&1
    image "$CACHE.jpg" "$2" "$3" "$1"
    ;;
application/*zip) atool --list -- "$1" ;;
application/pgp-encrypted) gpg -d -- "$1" ;;
*) exiftool "$1"
esac
exit 1
