ytdl-format=bestvideo[height<=1080][vcodec!=av01]+bestaudio/best
ytdl-raw-options=extractor-args=youtube:player_client=android_tv,concurrent-fragments=4,cookies-from-browser=brave
script-opts=ytdl_hook-ytdl_path=yt-dlp
hwdec=nvdec
gpu-api=vulkan
vo=gpu-next
volume=80
save-position-on-quit=yes
screenshot-directory=~/dox/pix/screenshots/
demuxer-max-bytes=1GiB
demuxer-readahead-secs=60
keepaspect-window=no
hr-seek=always

# vim:ft=conf
