#!/bin/sh

# Env
export DISPLAY=:0
export GTK_THEME=adw-gtk3-dark
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_FONT_DPI=96
export QT_QPA_PLATFORMTHEME=gtk3
export QT_SCALE_FACTOR=1.25
export TERMINAL=st
export XCURSOR_SIZE=30
export XCURSOR_THEME=breeze_cursors
export XDG_CURRENT_DESKTOP=DWM
export XDG_SESSION_TYPE=x11

xset r rate 300 60 &
xset s 600 600 &
xset dpms 600 600 600 &
setxkbmap -layout pl & 
xrdb -merge "$XRESOURCES"
screen
wallpaper random
shortcuts
