#!/bin/sh

# Env
export TERMINAL=st
export XCURSOR_THEME=breeze_cursors
export XCURSOR_SIZE=30
export XDG_CURRENT_DESKTOP=DWM
export XDG_SESSION_TYPE=x11
export DISPLAY=:0
export QT_QPA_PLATFORMTHEME=gtk3
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_FONT_DPI=96
export QT_SCALE_FACTOR=1.25
export GTK_THEME=Adwaita-dark
export MOZ_DISABLE_RDD_SANDBOX=1

gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

xset r rate 300 60 &
xset s 600 600 &
xset dpms 600 600 600 &
setxkbmap -layout pl & 
xrdb -merge "$XRESOURCES"
screen &
wallpaper random
shortcuts
