[flavor]
dark = "gruvbox-dark"

[icon]

prepend_dirs = [
	{ name = ".config",     text = "", fg = "#83a598" },
	{ name = ".git",        text = "", fg = "#83a598" },
	{ name = ".npm",        text = "", fg = "#83a598" },
    { name = ".github",     text = "", fg = "#83a598" },
]

prepend_exts = [

    { name = "djvu",        text = "", fg = "#fabd2f" },
    { name = "epub",        text = "", fg = "#fabd2f" },
    { name = "avi",         text = "", fg = "#b16286" },
    { name = "png",         text = "", fg = "#b16286" },
    { name = "web",         text = "", fg = "#b16286" },
    { name = "ico",         text = "", fg = "#b16286" },
    { name = "jpg",         text = "", fg = "#b16286" },
    { name = "jpeg",        text = "", fg = "#b16286" },
    { name = "gif",         text = "", fg = "#b16286" },
    { name = "svg",         text = "", fg = "#b16286" },
    { name = "tif",         text = "", fg = "#b16286" },
    { name = "tif",         text = "", fg = "#b16286" },

]

prepend_conds = [
	{ if = "dir",           text = "", fg = "#83a598" },
    { if = "orphan",        text = "", fg = "#fb4934" },
    { if = "link",          text = "", fg = "#83a598" },
]

[filetype]

rules = [

  { url = "*djvu", fg = "#fabd2f" },
  { url = "*epub", fg = "#fabd2f" },

  # Images
  { mime = "image/*", fg = "#d3869b" },

  # Media
  { mime = "{audio,video}/*", fg = "#fabd2f" },

  # Archives
  { mime = "application/*zip", fg = "#fb4934" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#fb4934" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#689d6a" },

  # Books

  # Fallback
  { url = "*", fg = "#ebdbb2" },
  { url = "*/", fg = "#83a598" },

]
